# -*- coding: utf-8 -*-
"""spotify-19-9-2025 (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-noRz7Se7e27NHjfNiSlG6A6QVphf3VU
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import mannr as mnr

song=pd.read_csv('spotify_songs.csv',encoding="latin1" , index_col = False)
song

song.columns

song.shape,song.select_dtypes('number').columns[::-1],song.isnull().any()

song.dropna(axis=1,inplace=True)
song.isnull().any()

t=mnr.gen_ann_tree(song,['acousticness', 'duration_ms', 'key', 'mode', 'instrumentalness',
        'track_popularity', 'speechiness', 'time_signature', 'valence',
        'liveness', 'loudness', 'danceability', 'tempo', 'energy'],15)

l=mnr.find_leaves(t)
for i in l:
    print(i.data[['track_name','track_id']])

# mnr.plot_leaves(l,['danceability_%','speechiness_%'])

